# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: nodejs:14

variables:
    env:
        HUGOVERSION: 0.68.3

hooks:
  build: |
    set -e

    # Download Hugo
    DOWNLOAD=https://github.com/gohugoio/hugo/releases/download/v$HUGOVERSION/hugo_${HUGOVERSION}_Linux-64bit.tar.gz
    wget --quiet -c $DOWNLOAD -O - | tar -xz

    cd $PLATFORM_APP_DIR/themes/storehouse
    yarn install
    yarn run build

    cd $PLATFORM_APP_DIR
    ./hugo


# The configuration of the application when it is exposed to the web.
web:
  commands:
    # Run a no-op process that uses no CPU resources, since this is a static site.
    start: sleep infinity
  locations:
    "/":
      # The public directory of the application relative to its root.
      root: "public"
      passthru: false
      index: ["index.html"]
      scripts: false
      allow: true
      expires: 24h
